name: mobdev_parte_01
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/ricdtaveira/mobdev-parte-01

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  http: ^1.2.2
  path: ^1.8.3
  flutter:
    sdk: flutter 
  sqflite: ^2.3.0
  sqlite3: ^2.5.0
dev_dependencies:
  lints: ^5.1.0
  test: ^1.21.0